FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y openssh-server && \
    mkdir /var/run/sshd

COPY keys/id_rsa.pub /tmp/jumpbox.pub

RUN useradd -m -s /bin/bash user1 && \
    mkdir -p /home/user1/.ssh && \
    cp /tmp/jumpbox.pub /home/user1/.ssh/authorized_keys && \
    chown -R user1:user1 /home/user1/.ssh && \
    chmod 700 /home/user1/.ssh && \
    chmod 600 /home/user1/.ssh/authorized_keys

RUN sed -i 's/#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config && \
    echo "StrictModes yes" >> /etc/ssh/sshd_config

CMD ["/usr/sbin/sshd", "-D"]
