version: "3.9"

services:
  ssh-jumpbox:
    build: .
    container_name: ssh_jumpbox
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - ./ssh:/ssh:ro
      - ./keys:/keys:ro
    environment:
      ADMIN_USER: "${ADMIN_USER}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      USERS: |
        host1;user1;host1.local;/keys/id_rsa;/ssh/authorized_keys
        host2;user2;host2.local;/keys/id_rsa;/ssh/authorized_keys
        host3;user3;host3.local;/keys/id_rsa;/ssh/authorized_keys
